### ISSUE TITLE
Router don't work with Preact (10.18.1)

### ISSUE THREAD

**Issue by Nicolab** [molefrog/wouter#382]
Hello,

First, thanks it's a nice router.

I just installed wouter, I encountered 2 errors.

1) Typescript error displayed by the linter in VS code: 

```
JSX element type 'Router' does not have any construct or call signatures.ts(2604)
'Router' cannot be used as a JSX component.
  Its type 'typeof import("/app/assets/node_modules/.pnpm/wouter-preact@2.12.1_preact@10.18.1/node_modules/wouter-preact/types/ts4.1/index")' is not a valid JSX element type.ts(2786)
 ```

--- 

2) JS Error displayed in the devTools: `matcher.js:64 Uncaught (in promise) TypeError: pattern.substring is not a function` 
In the `pathToRegexp` function, `result += escapeRx(pattern.substring(lastIndex));`

My code:

```tsx
<Router base="/superadmin">
      <Route path="/" component={SuperAdmin} />
      <Route path="/orgs" component={AdminOrgs} />
    </Router>
```

`<Switch /> component ` instead `<Router />` works.

**Comment by Nicolab** [comment]
My bad, I imported "Router" as with preact-router... It's friday 👻

**Comment by molefrog** [comment]
Haha, glad you figured it out. I was a bit stressed out when saw the first message ☺️happy Friday!

**Comment by Nicolab** [comment]
Haha, sorry for that 🤭 

Happy week-end!
